-- full projects table with corrected date formats
from projects_for_analytics
select
    "name",
    job_names,
    shared_drains,
    statuses,
    original_booking_date::DATE as original_booking_date,
    surveyed_by,
    report_by,
    eqc_claim_manager,
    total_quote_value,
    project_manager,
    assigned_to,
    site_staff,
    concreter,
    labour_hours,
    labour_cost_total,
    supplier_costs_total,
    total_costs,
    gross_profit,
    gp_margin_pct,
    est_proj_overhead,
    job_cards_urls,
    job_ids,
    latitude,
    longitude,
    quote_nos,
    variation_quote_nos,
    work_start::DATE as work_start,
    work_end::DATE as work_end,
    customer_details,
    qty_from_cards,
    timeline,
    labour_records,
    sum_qty_from_cards,
    xero_costs_linked
order by statuses
