from pathlib import Path

import polars as pl


def load_csv(file_path: Path) -> pl.DataFrame:
    """Loads CSV files to a dataframe, gets rid of nulls and unanmed columns like index columns generated by pandas"""
    return (
        pl.scan_csv(file_path)
        .fill_null("")
        .select([col for col in pl.scan_csv(file_path).columns if col.strip()])
        .collect()
    )
